// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrj8Ghu-N-pW52cx4a28272eYBp1Yfj_k',
    appId: '1:482784011901:web:31ea33973c95e658feb314',
    messagingSenderId: '482784011901',
    projectId: 'twitchauth-56a8a',
    authDomain: 'twitchauth-56a8a.firebaseapp.com',
    storageBucket: 'twitchauth-56a8a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU_8-Ax_7DzJWTRp2KzlAfdqVWFGLKjoo',
    appId: '1:482784011901:android:22355b2d713b160bfeb314',
    messagingSenderId: '482784011901',
    projectId: 'twitchauth-56a8a',
    storageBucket: 'twitchauth-56a8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo75VHjXjEZ5DYUFlQlLdn4e1HitumLWA',
    appId: '1:482784011901:ios:55d75b242fe151a3feb314',
    messagingSenderId: '482784011901',
    projectId: 'twitchauth-56a8a',
    storageBucket: 'twitchauth-56a8a.appspot.com',
    iosBundleId: 'com.example.twitch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo75VHjXjEZ5DYUFlQlLdn4e1HitumLWA',
    appId: '1:482784011901:ios:55d75b242fe151a3feb314',
    messagingSenderId: '482784011901',
    projectId: 'twitchauth-56a8a',
    storageBucket: 'twitchauth-56a8a.appspot.com',
    iosBundleId: 'com.example.twitch',
  );
}
